# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-13 00:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='portofolio_site',
            new_name='portfolio_site',
        ),
    ]
